flowchart TD
    A@{ img: "https://symbols.getvecta.com/stencil_240/1_10700.3c03389f5e.svg", label: "Image Label", pos: "t", w: 10, constraint: "off" } --> | XD | B@{ img: "https://symbols.getvecta.com/stencil_240/79_fileserver.c500813aaa.svg", label: "Image Label", pos: "d", constraint: "off" }


